# DatabaseCore Configuration
database:
  host: "localhost"
  port: 3306
  name: "minecraft"
  username: "root"
  password: "password"

# Connection pool settings
connection-pool:
  maximum-pool-size: 10
  minimum-idle: 5
  connection-timeout: 30000
  idle-timeout: 600000
  max-lifetime: 1800000

